name: make lint 
on: push
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Inastall Python
        uses: actions/setup-python@v2
        with:
         python-version: 3.8
      - name: Install depen
        run:  python -m pip install --upgrade pip
      - name: Install and configure Poetry
        uses: snok/install-poetry@v1
        with:
          version: 1.1.12
          virtualenvs.create: true
          virtualenvs.in-project: true
          virtualenvs.path: "{cache-dir}/virtualenvs"  # /home/xisp/.cache/pypoetry/virtualenvs 
      - name: Install depen
        run:  poetry add --dev wemake-python-styleguide
      - name: Command         
        run: make lint
